### PR TITLE
Update information about Polish filterlists.

### PR DESCRIPTION
**Pull request by hawkeye116477**
@ryanbr

### CODE REVIEW

**Comment by krystian3w** [comment]
@pes10k?

**Comment by pes10k** [comment]
@ryanbr what do you think? Looks good to me.

**Comment by ryanbr** [comment]
Looks fine, Does component_id and base64 id need to be updated @pes10k

**Comment by ryanbr** [comment]
LGTM.  Confirmed no other changes are needed

**Pull request merged**
