### PR TITLE
Updated NoCoin Filter List

### PR DESCRIPTION
**Pull request by TheAresjej**
2018 vs 2020

### CODE REVIEW

**Comment by ryanbr** [comment]
I'll review commit this week, Looking at merging fixes from https://github.com/hoshsadiq/adblock-nocoin-list possibly instead.

**Comment by TheAresjej** [comment]
@ryanbr what do you think of it? 😄

**Comment by ryanbr** [comment]
How was the diff created @TheAresjej  ?

**Comment by TheAresjej** [comment]
> How was the diff created @TheAresjej ?

I manually compared the changes and added new entries but in which case, if this update is not useful, it can be closed 😄

**Comment by ryanbr** [comment]
I'll re-checkout vs the current nocoin version, thanks for the reminder for requesting an update to the coin list :)

**Pull request closed without merging**
